version: "3.7"

services:
  s300_dispatcher:
    build:
      context: app
      dockerfile: Dockerfile
    image: hub.eis24.me/rs
    ports:
      - "8003:8003"
    command: ["python", "main.py"]
    restart: always
    env_file:
      - .env.docker

  s300_dispatcher_celery_worker:
    build:
      context: app
      dockerfile: Dockerfile
    command: ["celery", "-A", "celery_app", "worker", "--loglevel=info"]
    depends_on:
      - s300_dispatcher_redis
    env_file:
      - .env.docker

  s300_dispatcher_celery_beat:
    build:
      context: app
      dockerfile: Dockerfile
    command: ["celery", "-A", "celery_app", "beat", "--loglevel=info"]
    depends_on:
      - s300_dispatcher_redis
    env_file:
      - .env.docker

  s300_dispatcher_flower:
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "5558:5555"
    command: ["celery", "-A", "celery_app", "flower", "--port=5555"]
    depends_on:
      - s300_dispatcher_redis
    env_file:
      - .env.docker

  s300_dispatcher_redis:
    image: hub.eis24.me/redis:3.2.4
    restart: always
    ports:
      - "6380:6379"
    env_file:
      - .env.docker


  elasticsearch:
      image: elasticsearch:8.10.2
      container_name: elasticsearch
      environment:
        - xpack.security.enabled=false
        - discovery.type=single-node
        - ES_JAVA_OPTS=-Xms1g -Xmx1g
      ports:
        - "9200:9200"
        - "9300:9300"
      volumes:
        - ./es_data:/usr/share/elasticsearch/data